# Generated by Django 5.2.1 on 2025-06-26 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('date_publication', models.DateField(auto_now_add=True)),
                ('lien_drive', models.URLField(blank=True, null=True)),
                ('lien_externe', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Arrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('lien_drive', models.URLField(blank=True, null=True)),
                ('prix', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('date_publication', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lien_drive', models.URLField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GuideFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('lien_drive', models.URLField(blank=True, null=True)),
                ('prix', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('niveau', models.CharField(choices=[('Tle', 'Terminale'), ('1ère', 'Première'), ('2nde', 'Seconde'), ('3e', 'Troisième'), ('4e', 'Quatrième'), ('5e', 'Cinquième'), ('6e', 'Sixième'), ('Maternelle1', 'Maternelle 1'), ('Maternelle2', 'Maternelle 2'), ('CI', "Cours d'Initiation"), ('CP', 'Cours Préparatoire'), ('CE1', 'Cours Élémentaire 1'), ('CE2', 'Cours Élémentaire 2'), ('CM1', 'Cours Moyen 1'), ('CM2', 'Cours Moyen 2'), ('BTS', 'BTS'), ('Licence1', 'Licence 1'), ('Licence2', 'Licence 2'), ('Licence3', 'Licence 3'), ('Master1', 'Master 1'), ('Master2', 'Master 2'), ('Doctorat', 'Doctorat')], default='Tle', max_length=100)),
                ('annee', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('telechargements', models.PositiveIntegerField(default=0)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='FicheCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('lien_drive', models.URLField(blank=True, null=True)),
                ('prix', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('niveau', models.CharField(choices=[('Tle', 'Terminale'), ('1ère', 'Première'), ('2nde', 'Seconde'), ('3e', 'Troisième'), ('4e', 'Quatrième'), ('5e', 'Cinquième'), ('6e', 'Sixième'), ('Maternelle1', 'Maternelle 1'), ('Maternelle2', 'Maternelle 2'), ('CI', "Cours d'Initiation"), ('CP', 'Cours Préparatoire'), ('CE1', 'Cours Élémentaire 1'), ('CE2', 'Cours Élémentaire 2'), ('CM1', 'Cours Moyen 1'), ('CM2', 'Cours Moyen 2'), ('BTS', 'BTS'), ('Licence1', 'Licence 1'), ('Licence2', 'Licence 2'), ('Licence3', 'Licence 3'), ('Master1', 'Master 1'), ('Master2', 'Master 2'), ('Doctorat', 'Doctorat')], default='Tle', max_length=100)),
                ('annee', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('telechargements', models.PositiveIntegerField(default=0)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='Epreuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('Tle', 'Terminale'), ('1ère', 'Première'), ('2nde', 'Seconde'), ('3e', 'Troisième'), ('4e', 'Quatrième'), ('5e', 'Cinquième'), ('6e', 'Sixième'), ('Maternelle1', 'Maternelle 1'), ('Maternelle2', 'Maternelle 2'), ('CI', "Cours d'Initiation"), ('CP', 'Cours Préparatoire'), ('CE1', 'Cours Élémentaire 1'), ('CE2', 'Cours Élémentaire 2'), ('CM1', 'Cours Moyen 1'), ('CM2', 'Cours Moyen 2'), ('BTS', 'BTS'), ('Licence1', 'Licence 1'), ('Licence2', 'Licence 2'), ('Licence3', 'Licence 3'), ('Master1', 'Master 1'), ('Master2', 'Master 2'), ('Doctorat', 'Doctorat')], default='Tle', max_length=100)),
                ('titre', models.CharField(max_length=255)),
                ('lien_drive', models.URLField(blank=True, null=True)),
                ('lien_drive_corrige', models.URLField(blank=True, null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
                ('annee', models.PositiveIntegerField(default='2024')),
                ('telechargements', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.matiere')),
            ],
        ),
    ]
