# Generated by Django 5.2.1 on 2025-05-23 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epreuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to='epreuves/')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
                ('niveau', models.CharField(choices=[('Tle', 'Terminale'), ('1ère', 'Première'), ('2nde', 'Seconde'), ('3e', 'Troisième'), ('4e', 'Quatrième'), ('5e', 'Cinquième'), ('6e', 'Sixième'), ('CP', 'Cours Préparatoire'), ('CE1', 'Cours Élémentaire 1'), ('CE2', 'Cours Élémentaire 2'), ('CM1', 'Cours Moyen 1'), ('CM2', 'Cours Moyen 2'), ('6e', '6e'), ('5e', '5e'), ('4e', '4e'), ('3e', '3e'), ('2nde', '2nde'), ('1ère', '1ère'), ('Tle', 'Terminale'), ('BTS', 'BTS'), ('Licence', 'Licence')], default='Tle', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matière',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Matières',
        ),
        migrations.AddField(
            model_name='epreuve',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.matière'),
        ),
    ]
