# Generated by Django 5.2.1 on 2025-06-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_epreuve_niveau_fichecours'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichecours',
            name='telechargements',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
