# Generated by Django 5.2.1 on 2025-06-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_fichecours_telechargements'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichecours',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
