# Generated by Django 5.2.1 on 2025-06-08 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_fichecours_prix'),
    ]

    operations = [
    ]
