# Generated by Django 5.2.1 on 2025-06-08 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20250608_0436'),
        ('blog', '0007_auto_20250608_0438'),
    ]

    operations = [
    ]
