# Generated by Django 5.2.1 on 2025-06-08 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_merge_0007_auto_20250608_0436_0007_auto_20250608_0438'),
        ('blog', '0008_populate_matieres'),
    ]

    operations = [
    ]
