# Generated by Django 5.2.1 on 2025-06-11 04:15

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_epreuve_niveau_alter_fichecours_matiere_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epreuve',
            name='fichier',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='fichecours',
            name='fichier',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=''),
        ),
    ]
