# Generated by Django 5.2.1 on 2025-06-14 01:17

import cloudinary_storage.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_rename_matière_matiere_alter_epreuve_niveau_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('fichier', models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='')),
                ('date_publication', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuideFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('fichier', models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='')),
                ('niveau', models.CharField(choices=[('Tle', 'Terminale'), ('1ère', 'Première'), ('2nde', 'Seconde'), ('3e', 'Troisième'), ('4e', 'Quatrième'), ('5e', 'Cinquième'), ('6e', 'Sixième'), ('Maternelle1', 'Maternelle 1'), ('Maternelle2', 'Maternelle 2'), ('CI', "Cours d'Initiation"), ('CP', 'Cours Préparatoire'), ('CE1', 'Cours Élémentaire 1'), ('CE2', 'Cours Élémentaire 2'), ('CM1', 'Cours Moyen 1'), ('CM2', 'Cours Moyen 2'), ('BTS', 'BTS'), ('Licence1', 'Licence 1'), ('Licence2', 'Licence 2'), ('Licence3', 'Licence 3'), ('Master1', 'Master 1'), ('Master2', 'Master 2'), ('Doctorat', 'Doctorat')], default='Tle', max_length=100)),
                ('annee', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('telechargements', models.PositiveIntegerField(default=0)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.matiere')),
            ],
        ),
    ]
