# Generated by Django 5.2.1 on 2025-06-16 01:24

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='epreuve',
            name='fichier_corrige',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=''),
        ),
    ]
