# Generated by Django 5.2.1 on 2025-06-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_epreuve_fichier_corrige'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actualite',
            old_name='lien_externe',
            new_name='lien_drive',
        ),
        migrations.RemoveField(
            model_name='actualite',
            name='fichier',
        ),
        migrations.RemoveField(
            model_name='actualite',
            name='image',
        ),
        migrations.RemoveField(
            model_name='arrete',
            name='fichier',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.RemoveField(
            model_name='epreuve',
            name='fichier',
        ),
        migrations.RemoveField(
            model_name='epreuve',
            name='fichier_corrige',
        ),
        migrations.RemoveField(
            model_name='fichecours',
            name='fichier',
        ),
        migrations.RemoveField(
            model_name='guideformation',
            name='fichier',
        ),
        migrations.AddField(
            model_name='arrete',
            name='lien_drive',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arrete',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='document',
            name='lien_drive',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='epreuve',
            name='lien_drive',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='epreuve',
            name='lien_drive_corrige',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichecours',
            name='lien_drive',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guideformation',
            name='lien_drive',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guideformation',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='epreuve',
            name='annee',
            field=models.PositiveIntegerField(default='2024'),
        ),
    ]
