# Generated by Django 5.2.1 on 2025-06-17 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_rename_lien_externe_actualite_lien_drive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualite',
            name='lien_externe',
            field=models.URLField(blank=True, null=True),
        ),
    ]
