NIVEAUX = [
    ('Tle', 'Terminale'),
    ('1ère', 'Première'),
    ('2nde', 'Seconde'),
    ('3e', 'Troisième'),
    ('4e', 'Quatrième'),
    ('5e', 'Cinquième'),
    ('6e', 'Sixième'),
    ('Maternelle1', 'Maternelle 1'),
    ('Maternelle2', 'Maternelle 2'),
    ('CI', 'Cours d\'Initiation'),
    ('CP', 'Cours Préparatoire'),
    ('CE1', 'Cours Élémentaire 1'),
    ('CE2', 'Cours Élémentaire 2'),
    ('CM1', 'Cours Moyen 1'),
    ('CM2', 'Cours Moyen 2'),
    ('BTS', 'BTS'),
    ('Licence1', 'Licence 1'),
    ('Licence2', 'Licence 2'),
    ('Licence3', 'Licence 3'),
    ('Master1', 'Master 1'),
    ('Master2', 'Master 2'),
    ('Doctorat', 'Doctorat'),
]
